project_id = "fezajfdaydxtavjbabpt"

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.test-whatsapp]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false