// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fezajfdaydxtavjbabpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlemFqZmRheWR4dGF2amJhYnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTcxMjQsImV4cCI6MjA2Njg5MzEyNH0.bwHc-duXzsoarqcKx-vJmN8tmJKZ21l4VkXCUzNO_kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});